config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
   root to: 'homes#top'
  end

  namespace :admin do

    resources :customers, only: [:show, :index, :edit, :update, :new]
    # get 'genres/index'
    # get 'genres/edit'
    resources :genres, only: [:edit,:index,:create,:update]
    resources :items, only: [:new, :create, :edit, :update, :show,:index]
    resources :orders, only: [:show, :update]

    get 'homes/top'

  end


  namespace :public do

    get 'homes/about'
    patch '/customers/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    get 'orders/complete'
    resources :orders, only: [:index, :new, :show, :complete, :create] do
     collection do
       post :confirm
     end
    end
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
       delete 'destroy_all'
      end
    end
    resources :customers, only: [:index, :edit, :show, :update, :destroy]
    resources :items, only: [:show,:index]
  end



  # 顧客用
  devise_for :customers,skip: [:passwords], controllers: {
   registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
end


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
   belongs_to :item

   belongs_to :customer

def subtotal
    item.with_tax_price * amount
end


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image

  has_many :orders

  has_many :cart_items

  has_many :addresses, dependent: :destroy

  def active_for_authentication?
    super && (is_deleted == false)
  end


def address_display
  '〒' + postal_code + ' ' + address + ' ' + first_name + last_name
end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :item, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
 has_one_attached :image

 belongs_to :genre
 has_many :order_details

 has_many :cart_items, dependent: :destroy

# def add_tax_price
#   (self.price * 1.10).round
# end

def with_tax_price
    (price * 1.1).floor
end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }

  #enum shipping_cost: { money: 0, money_in: 1, make:2, send:3, sent:4}






end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord


  belongs_to :order
  belongs_to :item
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  
  enum making_status: { a: 0, b: 1, c: 2, d: 3 }
  
  def subtotal
    with_tax_price * self.amount
  end
  
  def with_tax_price
    (self.price * 1.1).floor
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all

  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])

    if @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
    flash[:alert] = "編集完了"

    else
      render :edit
    end
  end

  def show
    @customers = Customer.all
    @customer = Customer.find_by(id: params[:id])
  end

private

  def customer_params
   params.require(:customer).permit(:last_name, :last_name_kana, :email, :first_name, :first_name_kana, :postal_code, :address, :telephone_number,:page,:is_deleted)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController


  def create
      @genre = Genre.new(genre_params)
      @genre.save
      redirect_to admin_genres_path
  end

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])

    if @genre.update(genre_params)
    redirect_to admin_genres_path
    flash[:alert] = "新規登録完了"

    else
      render :edit
    end

  end

private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end

private

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def index
    @item = Item.new
    @items = Item.all.page(params[:page]).per(5)

  end

  def new
    @item = Item.new
    @genres = Genre.all

  end



  def show
    @item = Item.find(params[:id])
  end

  def edit
    @genres = Genre.all
    @item = Item.find(params[:id])
  end

  def update
    @genres = Genre.all
    @item = Item.find(params[:id])

    if @item.update(item_params)
    redirect_to admin_item_path(@item.id)
    flash[:alert] = "編集完了"

    else
      render :edit
    end
  end

private

  def item_params
    params.require(:item).permit(:name,:introduction,:image,:price,:genre_id,:page, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    public_customer_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path

  end
    protected


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">

<h2>会員情報編集</h2>

 <%= form_with model: @customer, url: admin_customer_path(@customer.id) do |f| %>
 <table>
   <tr>
     <th>氏名</th>
      <td>
        <%= f.text_field :first_name %>
        <%= f.text_field :last_name %>
      </td>
    </tr>

    <tr>
      <th>フリガナ</th>
          <td>
            <%= f.text_field :first_name_kana %>
            <%= f.text_field :last_name_kana %>
          </td>
    </tr>

    <tr>
      <th>郵便番号</th>
          <td>
            <%= f.text_field :postal_code %>
          </td>
    </tr>

    <tr>
      <th>住所</th>
          <td>
            <%= f.text_field :address %>
          </td>
    </tr>

    <tr>
      <th>電話番号</th>
          <td>
            <%= f.text_field :telephone_number %>
          </td>
    </tr>

    <tr>
      <th>メールアドレス</th>
          <td>
            <%= f.text_field :email%>
          </td>
    </tr>

    <tr>
      <th>会員ステータス</th>
          <td>
            <%= f.label :receive_news, '有効', value: 0 %>
            <%= f.radio_button :is_deleted , "0"%>
            <%= f.label :receive_news, '退会', value: 1 %>
            <%= f.radio_button :is_deleted , "1"%>
          </td>
    </tr>

    <tr>
      <td><%= f.submit '編集内容を保存',class:"btn btn-success" %></td>
    </tr>
<% end %>
 </table>

app/views/admin/customers/index.html.erb
<div class="container">

<h1>会員一覧</h1>

<table>
  <thead>
    <tr>
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>

    <tr>
      <td><%= customer.id %></td>
      <td>
        <%= link_to admin_customer_path(customer.id) do %>
          <%= customer.first_name %><%= customer.last_name %>
        <% end %>
      </td>
      <td><%= customer.email %></td>
      <td><%= customer.is_deleted ? '退会' : '有効'%></td>
    </tr>
    <% end %>

  </tbody>
</table>

app/views/admin/customers/show.html.erb
<div class="container">

 <h3><%= @customer.first_name %><%= @customer.last_name %>さんの会員詳細</h3>

<table>
  <tr>
    <th>会員ID</th>
    <td><%= @customer.id %></td>
  </tr>

  <tr>
    <th>氏名</th>
    <td><%= @customer.first_name %></td>
    <td><%= @customer.last_name %></td>
  </tr>

  <tr>
    <th>カナ</th>
    <td><%= @customer.first_name_kana %></td>
    <td><%= @customer.last_name_kana %></td>
  </tr>

  <tr>
    <th>郵便番号</th>
    <td><%= @customer.postal_code %></td>
  </tr>

  <tr>
    <th>住所</th>
    <td><%= @customer.address %></td>
  </tr>

  <tr>
    <th>電話番号</th>
    <td><%= @customer.telephone_number %></td>
  </tr>

  <tr>
    <th>メールアドレス</th>
    <td><%= @customer.email %></td>
  </tr>

  <tr>
    <th>会員ステータス</th>
    <td><%= @customer.is_deleted ? '退会' : '有効' %></td>
  </tr>
</table>

<%= link_to edit_admin_customer_path(@customer.id), class: "btn btn-success" do %>編集する
<% end %>

<%= link_to public_orders_path, class: "btn btn-info" do %>注文一覧を見る
<% end %>