config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
   root to: 'homes#top'
  end

  namespace :admin do

    resources :customers, only: [:show, :index, :edit, :update, :new]
    # get 'genres/index'
    # get 'genres/edit'
    resources :genres, only: [:edit,:index,:create,:update]
    resources :items, only: [:new, :create, :edit, :update, :show,:index]
    resources :orders, only: [:show, :update]

    get 'homes/top'

  end


  namespace :public do

    get 'homes/about'
    patch '/customers/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    get 'orders/complete'
    resources :orders, only: [:index, :new, :show, :complete, :create] do
     collection do
       post :confirm
     end
    end
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
       delete 'destroy_all'
      end
    end
    resources :customers, only: [:index, :edit, :show, :update, :destroy]
    resources :items, only: [:show,:index]
  end



  # 顧客用
  devise_for :customers,skip: [:passwords], controllers: {
   registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
end


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
   belongs_to :item

   belongs_to :customer

def subtotal
    item.with_tax_price * amount
end


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image

  has_many :orders

  has_many :cart_items

  has_many :addresses, dependent: :destroy

  def active_for_authentication?
    super && (is_deleted == false)
  end


def address_display
  '〒' + postal_code + ' ' + address + ' ' + first_name + last_name
end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :item, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
 has_one_attached :image

 belongs_to :genre
 has_many :order_details

 has_many :cart_items, dependent: :destroy

# def add_tax_price
#   (self.price * 1.10).round
# end

def with_tax_price
    (price * 1.1).floor
end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }

  #enum shipping_cost: { money: 0, money_in: 1, make:2, send:3, sent:4}






end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord


  belongs_to :order
  belongs_to :item
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  
  enum making_status: { a: 0, b: 1, c: 2, d: 3 }
  
  def subtotal
    with_tax_price * self.amount
  end
  
  def with_tax_price
    (self.price * 1.1).floor
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController


  def create
      @genre = Genre.new(genre_params)
      @genre.save
      redirect_to admin_genres_path
  end

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])

    if @genre.update(genre_params)
    redirect_to admin_genres_path
    flash[:alert] = "新規登録完了"

    else
      render :edit
    end

  end

private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end

private

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def index
    @item = Item.new
    @items = Item.all.page(params[:page]).per(5)

  end

  def new
    @item = Item.new
    @genres = Genre.all

  end



  def show
    @item = Item.find(params[:id])
  end

  def edit
    @genres = Genre.all
    @item = Item.find(params[:id])
  end

  def update
    @genres = Genre.all
    @item = Item.find(params[:id])

    if @item.update(item_params)
    redirect_to admin_item_path(@item.id)
    flash[:alert] = "編集完了"

    else
      render :edit
    end
  end

private

  def item_params
    params.require(:item).permit(:name,:introduction,:image,:price,:genre_id,:page, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
      admin_homes_top_path
    else
      admin_session_path
    end

    end

  def after_sign_out_path_for(resource_or_scope)
      if resource_or_scope == :admin
        admin_session_path
      end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  # def after_sign_out_path_for(resource)
  #   root_path
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    public_customer_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path

  end
    protected


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
　　<div class="container">

　　<div class="col-md-3">
　　<h2 class="shadow- p-3 mb-5 bg-light">ジャンル編集</h2>
　　 </div>
　　    <%= form_with model: @genre,url: admin_genre_path do |f| %>
      <table>
        <tr>
          <th>ジャンル名</th>
          <th><%= f.text_field :name %></th>
          <th><%= f.submit '変更を保存',class:"btn btn-success" %></th>
        </tr>
      </table>

　　<% end %>
　　</div>

app/views/admin/genres/index.html.erb
<div class="container">

<h1>ジャンル一覧・追加</h1>

<div class="col-md-3">
      <%= form_with model: @genre,url: admin_genres_path, method: :POST do |f| %>
          <h4>ジャンル名</h4>
          <table>
              <tr>
                <th><%= f.text_field :name %></th>
                <th><%= f.submit '新規登録' ,class:"btn btn-success" %></th>
              </tr>
          </table>

<table class="table table-hover table-inverse">
  <thead>
   <tr>
   <th><h4>ジャンル</h4></th>
    </thead>

    <tbody>
 　      <% @genres.each do |genre| %>
 　      <tr>
 　      <td> <%= genre.name %> </td>
 　      <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class:"btn btn-success" %></td>

 　      </tr>


   <% end %>

</table>
</div>
</div>
<% end %>

app/views/admin/items/edit.html.erb
<div class="container">

<h1>商品編集</h1>

　　<%= form_with model: @item ,url: admin_item_path(@item.id) do |f| %>
      <table>
        
        <tr>
          <th>商品画像</th>
          <th><%= f.file_field :image, accept: "image/*" %></th>
        </tr>
        
        <tr>
          <th>商品名</th>
          <th><%= f.text_field :name %></th>
        </tr>
      
        <tr>
          <th>商品説明</th>
          <th><%= f.text_area :introduction %></th>
        </tr>
        
        <tr>
          <th>ジャンル</th>
          <th><%= f.collection_select :genre_id, Genre.all, :id, :name %></th>
        </tr>
        
        <tr>
          <th>税抜価格</th>
          <th><%= f.number_field :price %>円</th>
        </tr>
        
      </table>
      
      </br>
      <%= f.submit '変更を保存',class:"btn btn-success" %>

　　<% end %>
　　
　　

app/views/admin/items/index.html.erb
<div class="container">
  
<h2>商品一覧</h2>
  <div>
    <%= link_to new_admin_item_path do %>
    <追加>
    <% end %>
  </div>

<table>
  <thead>
   <tr>
     <th>商品ID</th>
     <th>商品名</th>
     <th>税抜価格</th>
     <th>ジャンル</th>
   </tr>
  </thead>
  <% @items.each do |item| %>
  
  <tbody>
   <tr>
     <th><%= item.id %></th>
     <th>
       <%= link_to admin_item_path(item.id) do %>
        <%= item.name %>
       <% end %>
     </th>
     <th><%= item.price %>円</th>
     <th><%= item.genre.name %></th>
   </tr>
  </tbody>
  <% end %>
  


  
  
</table>

 <%= paginate @items %>

app/views/admin/items/new.html.erb
<div class="container">

<h1>商品新規登録</h1>
   <%= form_with model: @item,url: admin_items_path, method: :POST do |f| %>

<table>
   <tr>
     <th>商品画像</th>
     <th><%= f.file_field :image, accept: "image/*" %></th>
  </tr>

   <tr>
     <th>商品名</th>
     <th><%= f.text_field :name %></th>
  </tr>

  <tr>
     <th>商品説明</th>
     <th><%= f.text_area :introduction %></th>
  </tr>

   <tr>
     <th>ジャンル</th>
     <th><%= f.collection_select :genre_id, Genre.all, :id, :name %></th>
   </tr>

   <tr>
     <th>税抜価格</th>
     <th><%= f.number_field :price %>円</th>
   </tr>

   <tr>
     <th>販売ステータス</th>
     <td>
       <%= f.radio_button :is_active, "true" %>
       <%=f.label :is_active, "販売中" %>
     </td>
     <td>
       <%= f.radio_button :is_active, "false" %>
       <%=f.label :is_active, "販売停止中" %></td>
  </tr>

   <tr><td> <%= f.submit '新規登録',class:"btn btn-success" %> </tb></tr>
</table>

   <% end %>

</div>

app/views/admin/items/show.html.erb
<div class="container">

  <%=   flash[:alert]  %>

<h1>商品詳細</h1>
<table>
  <th><%= image_tag @item.image, size: "200x200" %></th>
  <tr>
    <th>商品名</th>
    <td><%= @item.name %></td>
  </tr>

  <tr>
  <th>商品説明</th>
  <td><%= @item.introduction %></td>
  </tr>

  <tr>
  <th>ジャンル</th>
  <td><%= @item.genre.name%></td>
  </tr>

  <tr>
  <th>税込価格(税抜価格)</th>
  <td><%= @item.with_tax_price.to_s(:dalimited) %>円(<%= @item.price.to_s(:delimited) %>円)</td>
  <td></td>
  </tr>

  <tr>
  <th>販売ステータス</th>
  <td><%= @item.status %></td>
  <td></td>
  </tr>


</table>

  <%= link_to edit_admin_item_path(@item.id), class: "btn btn-success" do %>編集する
  <% end %>

app/views/admin/orders/show.html.erb
<h2><%= @order.customer.first_name %><%= @order.customer.last_name %>さんの注文履歴</h2>

 <table>

   <tr>
      <th>購入日時</th>
      <th>注文個数</th>
   </tr>

   <tr>
     <td><%= @order.created_at.strftime('%Y/%m/%d %H:%M') %></td>

  <% @order.order_details.each do |order_detail| %>
     <td><%= order_detail.amount %></td>
  <% end %>

   </tr>


 </table>