config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
   root to: 'homes#top'
  end

  namespace :admin do

    resources :customers, only: [:show, :index, :edit, :update, :new]
    # get 'genres/index'
    # get 'genres/edit'
    resources :genres, only: [:edit,:index,:create,:update]
    resources :items, only: [:new, :create, :edit, :update, :show,:index]
    resources :orders, only: [:show, :update]

    get 'homes/top'

  end


  namespace :public do

    get 'homes/about'
    patch '/customers/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    get 'orders/complete'
    resources :orders, only: [:index, :new, :show, :complete, :create] do
     collection do
       post :confirm
     end
    end
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
       delete 'destroy_all'
      end
    end
    resources :customers, only: [:index, :edit, :show, :update, :destroy]
    resources :items, only: [:show,:index]
  end



  # 顧客用
  devise_for :customers,skip: [:passwords], controllers: {
   registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
end


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
   belongs_to :item

   belongs_to :customer

def subtotal
    item.with_tax_price * amount
end


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image

  has_many :orders

  has_many :cart_items

  has_many :addresses, dependent: :destroy

  def active_for_authentication?
    super && (is_deleted == false)
  end


def address_display
  '〒' + postal_code + ' ' + address + ' ' + first_name + last_name
end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :item, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
 has_one_attached :image

 belongs_to :genre
 has_many :order_details

 has_many :cart_items, dependent: :destroy

# def add_tax_price
#   (self.price * 1.10).round
# end

def with_tax_price
    (price * 1.1).floor
end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }

  #enum shipping_cost: { money: 0, money_in: 1, make:2, send:3, sent:4}






end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord


  belongs_to :order
  belongs_to :item
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  
  enum making_status: { a: 0, b: 1, c: 2, d: 3 }
  
  def subtotal
    with_tax_price * self.amount
  end
  
  def with_tax_price
    (self.price * 1.1).floor
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController


  def create
      @genre = Genre.new(genre_params)
      @genre.save
      redirect_to admin_genres_path
  end

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])

    if @genre.update(genre_params)
    redirect_to admin_genres_path
    flash[:alert] = "新規登録完了"

    else
      render :edit
    end

  end

private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end

private

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def index
    @item = Item.new
    @items = Item.all.page(params[:page]).per(5)

  end

  def new
    @item = Item.new
    @genres = Genre.all

  end



  def show
    @item = Item.find(params[:id])
  end

  def edit
    @genres = Genre.all
    @item = Item.find(params[:id])
  end

  def update
    @genres = Genre.all
    @item = Item.find(params[:id])

    if @item.update(item_params)
    redirect_to admin_item_path(@item.id)
    flash[:alert] = "編集完了"

    else
      render :edit
    end
  end

private

  def item_params
    params.require(:item).permit(:name,:introduction,:image,:price,:genre_id,:page, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    public_customer_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path

  end
    protected


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
      <ul class="navbar-nav ml-auto">

        <% if admin_signed_in? %>
            <li><%= link_to "ログアウト" ,destroy_admin_session_path, method: :delete %></li>
          　<li><%= link_to "商品一覧" ,admin_items_path %></li>
          　<li><%= link_to "会員一覧" ,admin_customers_path %></li>
          　<li><%= link_to "注文一覧" ,admin_homes_top_path %></li>
          　<li><%= link_to "ジャンル一覧" ,admin_genres_path %></li>
        <% else %>
            <li><%= link_to "ログイン", admin_session_path %></li>

        <% end %>

      <% if customer_signed_in? %>


          <li><%= link_to "マイページ" ,public_customer_path(current_customer) %></li>
          <li><%= link_to "商品一覧" ,public_items_path %></li>
          <li><%= link_to "カート" ,public_cart_items_path %></li>
          <li><%= link_to "注文履歴" ,public_orders_path %></li>
          <li><%= link_to "ログアウト" ,destroy_customer_session_path, method: :delete %></li>

      <% else %>
          <li>About</li>
          <li>商品一覧</li>
          <li><%= link_to "新規登録" ,new_customer_registration_path %></li>
          <li><%= link_to "ログイン", customer_session_path %></li>
      <% end %>
       </ul>
      </nav>
    </header>



    <%= yield %>
      <div class="container mt-5">
      <div class="row">
      <div class="mx-auto">

      <p>ながのcake</p>

    </footer>
  </body>
</html>